### ISSUE TITLE
Brainstorming on project name and logo.

### ISSUE THREAD

**Issue by eridincu** [bounswe/bounswe2020group4#23]
Everyone should think about the project name and logo and come up with an idea if possible until the next meeting.

Ideas can be added [here](https://github.com/bounswe/bounswe2020group4/wiki/Ideas-for-project-name-and-logo)

- [ ] Burak Çuhadar
- [x] Koray Çetin
- [x] Eylül Yalçınkaya
- [ ] Mehmet Erdinç Oğuz
- [x] Emre Girgin
- [x] Salih Kasım Benli
- [x] Berke Özdemir
- [ ] Katariina Korolainen
- [ ] Berkay Alkan
- [ ] Muhammed Olcayto Türker
- [x] Çağrı Çiftçi

**Comment by egirgin** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Brainstorming on project name and logo.](https://trello.com/c/jbfGqCwI/44-brainstorming-on-project-name-and-logo)

**Comment by egirgin** [comment]
I have checked the [top E-Commerce websites](https://www.similarweb.com/ja/top-websites/category/e-commerce-and-shopping) worldwide and their logos. The brand comes to the forefront rather than the logo as far as I see. Here are some examples:
- [Amazon](https://lh3.googleusercontent.com/proxy/ncz_4eaFxgdni1wNLIEmNREZSBmXdy0oBFM1MbvcPrt1yykEwU18_8LbcZFu6qGuhQuKT7izbs3sdaiOo6Q7kqTBnrNH0ZgdTXYPucBE-Nv1hPq6FKMVElACSBS_6-s6TNd1OsXedvOIu8z4LWXax0mL28mTN54)
- [Aliexpress](https://morfikirler.com/uploads/cache/alibaba-ve-aliexpress-uzerinden-alisveris-825x450.jpg)
- [Ebay](https://ir.ebaystatic.com/cr/v/c1/ebay-logo-1-1200x630-margin.png)
- [Rakuten](https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Rakuten_Global_Brand_Logo.svg/1024px-Rakuten_Global_Brand_Logo.svg.png)
- [Walmart](https://cdn.webrazzi.com/uploads/2018/10/Walmart.jpg)

Even the ones in Turkey:
- [Hepsiburada](https://is3-ssl.mzstatic.com/image/thumb/Purple114/v4/11/07/34/11073481-60ee-ece2-ef1b-d2476f0c2e61/AppIcon-iPhone-0-1x_U007emarketing-0-0-GLES2_U002c0-512MB-sRGB-0-0-0-85-220-0-0-0-5.png/246x0w.png)
- [GittiGidiyor](https://i4.hurimg.com/i/hurriyet/75/750x422/5e1dd11d2269a21f20092d8d.jpg)
- [trendyol](https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQtX-Ex3wmiVqdqMGPUWg2cSLq5Yh4ImJi113AGrJjA4BhD_7RB)

Hence, we should more focus on the name of the project rather than the logo or the mascot. Then we can make some adjustments on the name of it, like the one of **amazon** or **aliexpress**.

**Comment by berkeozdemir2016400246** [comment]
Not opening a new issue for this one but the new deadline is 11.03.2020. Everyone, please come up with at least one brand name and logo idea before then so we can vote and pick one.

**Comment by egirgin** [comment]
Options are closed and a poll is available at that [issue](https://github.com/bounswe/bounswe2020group4/issues/43).
