### ISSUE TITLE
Prepare the web app scenario for the Customer.

### ISSUE THREAD

**Issue by eridincu** [bounswe/bounswe2020group4#28]
Prepare and document the customer scenario **until Sunday 23.59.**

**Comment by egirgin** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Prepare the web app scenario for the Customer.](https://trello.com/c/vOHHoXMM/48-prepare-the-web-app-scenario-for-the-customer)

**Comment by egirgin** [comment]
Since we are going to prepare a web app mockup for 2 [scenarios](https://github.com/bounswe/bounswe2020group4/issues/29) with web app, there must be consistency in their UI. Probably we will design one this **Saturday (Feb 29)**. If you design one before we do, please share the wireframe with us, so we can design a consistent one.

**Comment by egirgin** [comment]
@zeritte and I made our mock-ups using [MockFlow](https://www.mockflow.com/). You can use the pages we created by logging in with our account. We can share the username and password with you if you want so.
