### ISSUE TITLE
Giving feedback on scenarios and mock-ups

### ISSUE THREAD

**Issue by berkeozdemir2016400246** [bounswe/bounswe2020group4#37]
Last week scenarios and mock-ups related to them were done. Now we need feedback to improve those scenarios. Feedbacks can be added to comments of this issue.

Deadline: 07/03/2020 @ 23.59

Scenario: Customer
- [x] Eylül Yalçınkaya
- [x] Burak Çuhadar
- [ ] Çağrı Çiftçi

Scenario: Vendor
- [x] Eylül Yalçınkaya
- [x] Burak Çuhadar
- [ ] Çağrı Çiftçi

Scenario: Guest
- [x] Eylül Yalçınkaya
- [x] Burak Çuhadar
- [ ] Çağrı Çiftçi

**Comment by eylulyalcinkaya** [comment]
### Scenario: Customer ###
- Actions does not include searching and filtering for a hat and then wishlisting it, this way we would be showcasing filtering etc.
- In the preconditions, it is said that Selim is already logged in but in mock-up log-in process is showed, this may not be necessary.
- In the mock-up, the notification page should be added.
- Some of the pictures is not showing, it should be fixed.
- In the mock-up, sorting according to product rating option should be added.
- Hats should be named other than Hat4, Hat5 etc. as the instructor mentioned during the lecture.
- A checkbox for accepting “uzaktan satış sözleşmesi” in checkout should be added.
- Boxes for card information should be filled with random information (like 1111111111111111 for card number).
- Actions include checking product comments but comments are not shown in mockup.

### Scenario: Guest ###
- Requirements should be written in full form in acceptance criteria.
- In mockup, sample images for products and a sample logo should be added.
- Sample reviews should be added.
- If the guest user has to sign up to buy a product, this should be added to requirements separately(e.g. Guest user has to sign up to buy a product.)

### Scenario: Vendor ###
- What kind of products is Ahmet selling? 
- I think it should be obligatory to add the stock amount when a vendor is adding a product to the site, so that when a product is sold, the site automatically decreases the stock. The vendor can manually change the stock amount or disable the product. The vendor can manually cancel an order. 
- Actions are written to the acceptance criteria, actions should be separate and acceptance criteria should include requirements in full sentences.
- Some pictures is not showing, it should be fixed.
- Sample product images and names should be added.
- In mockup 6: “the customers who added that product to his favorite list, gets notified. “. I don’t think we should be showing how the customers get notified since this scenario is about the vendor.

**Comment by eylulyalcinkaya** [comment]
**Here is the instructor's feedback from Piazza**

Group 4 - Feedback for the Scenarios and Mock-ups
Dear members of Group 4,
 
Below, you may find my feedbacks related to your scenarios and mock-ups. Please note that given feedback is not limited to ones below, you can apply similar comments to others if fits.
 
Besides stating the requirement number, you should also specify the requirement itself in the acceptance criteria (not stated in Sasha’s scenario).
 
The first mock-up (customer mock-up) does not contain a sufficient amount of real input data both in terms of text and image. Also, there is a Google ad, which should not exist in our platform. Also, during the checkout, you are showing recommended products to the user, which is absurd.
 
There is a question mark in the second, fifth, and sixth items of the vendor mock-up. You should either re-upload it or change the resolution of the image to be seen. Also, similar comments to the customer mock-up apply here as well (e.g., no image of the product, no product details). My suggestion is to remake the vendor mock-up from scratch.
 
Very similar comments apply for guest user mock-up as well (e.g., no product name, no product image, no reviews). Also, does a guest user have to sign-in to buy a product?
 
Best,
Meriç

**Comment by burakcuhadar** [comment]
### Customer Scenario
- Third and fifth images are not displayed properly.
- In the second image it is shown that there are two items in the cart, but in the following images they disappear.
- The first action is: "Selim creates a wishlist and adds his favorite hats." However in the mockup it is not shown how to create a wishlist and add items to it. 

### Vendor Scenario
- What is "Your Products" page? Is it different from the "Orders Page"? We can add it to requirements, if it is different. If you meant orders page, then "your products" should be changed to "orders page".
- In the scenario part Ahmet realizes that one of the orders is out of stock, but in the mockup there isn't any screenshot showing this situation. In addition, maybe some indicator can be added to show where the vendor clicks to cancel the order.

### Guest Scenario
- The last image shows that users can sign up with Facebook accounts, but we do not have a requirement about it. Either we should add it to our requirements, or we should remove that option from the mockup.

Suggestion for Customer and Vendor Scenarios: In the mockup of guest scenario there are arrows indicating where the user taps. I think that makes the mockup clearer and finding the relevant parts from mockup images becomes easier.
