### ISSUE TITLE
Asking questions that prepared in the meeting to the TA

### ISSUE THREAD

**Issue by cagric0** [bounswe/bounswe2020group4#58]
Deadline: 05.05.2020 Tuesday@23:59

**Comment by egirgin** [comment]
I got the response and summarizing here:

**Q1**. Are we going to use 11 APIs and implement 11 different APIs for each member or only 1 for the whole group?
**A1**. There is not any lower limit for the number APIs, so you don't have to implement 11 different APIs. Every member of the group must implement an **endpoint** rather than an API.  This may be possible by using/implementing 5 or 8 APIs. Actually, the number depends on the functionalities of the API you have chosen. However, every member of the group must implement a **unit test** and create a **pull request** at least one.

**Q2**. Does every member of the group need to use a different API? For instance, Can two members of the group implement two different APIs by using the Google Geolocation API?
**A2**. The chosen APIs don't need to be unique. Therefore you can implement different APIs using the same API.

**Q3**. Do we have to implement a single Front-end or a different front-end per API? What is the expected functionality of the Front-end? Do we need to use any other technology other than Pure HTML/CSS/JS?
**A3**. Pure HTML/CSS/JS should be enough. You don't need to implement a complex front-end. It is enough to have functionalities that can test the functionalities of the APIs you have implemented.

**Q4**. Do we need to create a **database** to test our APIs and filling it with dummy data? If so, do we need to deploy it to the AWS?
**A4**. Yes, you need to create one and deploy it to AWS. However, your dummy data must not be something like _aassadads_, the data should be consistent with your target audience like the ones you mentioned in the scenarios. 

**Q5**. "API Development" link on the piazza, routes to Swagger. However, if we are going to implement our API in Python/Java/JS. Then for which functionality are we going to use Swagger during our implementation phase? Only for the documenting?
**A5**. You may use Swagger for the documenting. The tools like Swagger/RAML/API Blueprint are intended to be helpful during both the implementation and documentation phases. It is up to you in which phase you are going to use. For us, it does not matter if you provide a well-documented API. 

**Q6**. Can we use nodeJS?
**A6**. Yes, you can.
